### PR TITLE
Fail on bad performance

### LINKED ISSUE #29: Make compareBenchmark task fail if the benchmark has bad results
The `compareBenchmark` task should fail if the benchmark comparison has bad results `master < branch` so we could use it when the `CI` task is not available

### PR DESCRIPTION
**Pull request by AdrianRaFo**
Fixes #29
Now the comparison tasks should fail if the benchmark contains bad performances. Furthermore, the CI task will execute the regular one if one of the CI parameters is not available

### CODE REVIEW

File: src/main/kotlin/com/fortysevendeg/hood/BenchmarkFilter.kt [hunk 1]
```diff
@@ -19,3 +23,13 @@ fun List<Benchmark>.filterBenchmarkIE(
   includeRegex: Option<Regex>,
   excludeRegex: Option<Regex>
 ): List<Benchmark> = filterBenchmark(includeRegex).filterBenchmarkNot(excludeRegex)
+
+fun List<BenchmarkComparison>.getWrongResults(): List<BenchmarkComparison> =
+  this.filter { it.result::class == BenchmarkResult.FAILED::class }
+
+fun List<BenchmarkComparison>.handleFailures(): Either<BenchmarkComparisonError, List<BenchmarkComparison>> {
+  val failures = this.getWrongResults()
```
Comment (fedefernandez) [inline src/main/kotlin/com/fortysevendeg/hood/BenchmarkFilter.kt]: Can we express this with something like:
```kotlin
NonEmptyList.fromList(failures.nonEmpty()).toRight(this.right).map(BenchmarkComparisonError(BadPerformanceBenchmarkError(it)))
```
